### PR TITLE
Handle python2.7 UnicodeDecodeError

### PR DESCRIPTION
**Pull request by mattgaff**

### CODE REVIEW

**Comment by mattgaff** [comment]
In relation to ticket: https://github.com/DavidMuller/aws-requests-auth/issues/24#issuecomment-318218550

**Comment by DavidMuller** [comment]
Thanks for this pull request @mattgaff. Can you provide...

- The version of python you are using
- Update this PR to include a "failing" test case that demonstrates how you are able to trigger the `UnicodeDecodeError` mentioned in https://github.com/DavidMuller/aws-requests-auth/issues/24#issuecomment-318218550:
 > I get the error ```UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 106185: ordinal not in range(128)```
> **This is where the problem started for me (line 106):**
> https://github.com/DavidMuller/aws-requests-auth/blob/master/aws_requests_auth/aws_auth.py#L104-L108

**Comment by CCP-Aporia** [comment]
Hi, I've run into the same problem with the `UnicodeDecodeError`. 
My scenario is a web-service that receives log files from various clients via HTTP.
wondered why the UTF-8 encoding is happening at all? [The AWS Documentation](https://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html#sig-v4-examples-post) explicitly states that a general UTF-8 encoding is not required for generating the signature:

> **NOTE**
>
> The following examples use UTF-8 to encode the canonical request and string to sign, but Signature Version 4 does not require that you use a particular character encoding. However, some AWS services might require a specific encoding. For more information, consult the documentation for that service.

I think the simplest solution is to always pipe the raw data into the signature algorithm without performing the UTF-8 encoding. That leaves the responsibility of correctly encoding data for the AWS services to the user of this module..

**Comment by DavidMuller** [comment]
@CCP-Aporia https://github.com/DavidMuller/aws-requests-auth/pull/21 originally introduce the utf-8 encoding for python 3 compatibility

**Comment by DavidMuller** [comment]
Duplicated by https://github.com/DavidMuller/aws-requests-auth/pull/30 -- which was released in [version 0.4.1](https://github.com/DavidMuller/aws-requests-auth/commit/bd638ea84903e4c2f482dbade610eb978c0a240e)

**Pull request closed without merging**
