### PR TITLE
Changes to make the library wok with Python3. Tested with Python 3.4.…

### PR DESCRIPTION
**Pull request by anantasty**
…3.NOTE: Changes are not backward compatible

### CODE REVIEW

**Comment by anantasty** [comment]
These changes are not backward compatible. These may need to go in a separate fork/ branch.

**Comment by DavidMuller** [comment]
Thanks for your work here @anantasty 

> These changes are not backward compatible. These may need to go in a separate fork/ branch.

Is there anything in particular stopping us from making backwards compatible changes?  I don't have much experience with creating python2 + python3 compatible projects, but is, roughly, something like this possible: `"if python3, from urllib.parse import urlparse, quote"`, `"elif python2, from urllib import urlparse, quote"`?

**Comment by anantasty** [comment]
We could a library such as six to make that possible. I just wanted to put
these out there. I can work on a more elegant fix some time

**Comment by anantasty** [comment]
So i added six as a requirement which is an elegant way to handle this issue. We could also resort to a

```
try:
    import python2-lib
except ImportError:
    import python3-lib
```

instead of using six so we arent bloating the package.

**Comment by jlaine** [comment]
I have submitted an alternative approach for supporting python2 + python3, which does not use six in #16

**Comment by DavidMuller** [comment]
python3 to should be added by https://github.com/DavidMuller/aws-requests-auth/pull/16

**Pull request closed without merging**
