### PR TITLE
Fixes bug with Multiple GET parameters

### PR DESCRIPTION
**Pull request by Entropius**

### CODE REVIEW

**Comment by DavidMuller** [comment]
thanks @Entropius -- would you mind updating [the tests](https://github.com/DavidMuller/aws-requests-auth/blob/master/aws_requests_auth/tests/test_aws_auth.py) to cover these new changes

I just added travis to the repo this morning, so if you push to to this pull request, travis *should* kick a build off for you

**Comment by Entropius** [comment]
Sorry, I will write new tests soon!

**Comment by DavidMuller** [comment]
thanks for the fix @Entropius

**Comment by DavidMuller** [comment]
these changes are now live on [pypi](https://pypi.python.org/pypi/aws-requests-auth) in version 0.2.3

**Pull request merged**
