### PR TITLE
Add boto3 integration to dynamically grab AWS credentials at runtime 

### PR DESCRIPTION
**Pull request by schobster**
Enable the ability to create an AWSRequestsAuth instance without explicitly passing AWS keys/tokens. The credentials will be dynamically pulled from the system by the AWS boto3 package, following its precedence order:
http://boto3.readthedocs.io/en/latest/guide/configuration.html#configuring-credentials

One thing to take a look at is how I have incorporated this into the AWSRequestsAuth constructor. One way would be to reorganize the constructor params to continue explicitly requiring the non-key/token params. This would be a breaking change though, so I opted instead to make all constructor params optional (which is non-ideal). Definitely open to suggestions on the best way to handle this change, but it seems most natural to modify the existing class rather than create something external to AWSRequestsAuth.

### CODE REVIEW

**Comment by schobster** [comment]
@DavidMuller here is a PR my friend

**Comment by thesmallestduck** [comment]
@schobster thanks for the PR. We've had a similar one before that we rejected: https://github.com/DavidMuller/aws-requests-auth/pull/10

Mainly we do not like the idea of introducing boto3 as a requirement. Believe it or not, we frequently run elasticsearch-py and aws-requests-auth in production environments without boto3 or botocore. Generally I agree this convenience would be nice, but it seems not too onerous a price to pay for keeping the reqs of this lib very very minimal. Open to discussion, of course.

**Comment by schobster** [comment]
@thesmallestduck that makes sense, and I can totally see that aws-requests-auth can be used in production without it. 

My main use case is to make it simpler to run the same script/tool anywhere that AWS credentials can be acquired, from my machine to a docker image on our Kubernetes cluster, with the additional flexibility that boto's built-in credential-gathering provides(8 different options for providing credentials), and without the need to follow a consistent pattern of environment variables/config files/etc. across all platforms that my script using aws-requests-auth could be run on.

I totally get keeping the reqs of this lib minimal, though I imagine that many people using this package will also have boto3 installed for other purposes, so that makes it less likely that adding this requirement will increase the package's footprint. Also, if (as you noted) other people have thought of features to add to aws-requests-auth which require boto3, I imagine more ideas will come in the future and at some point it may make sense to bite the bullet and add it as a requirement.

**Comment by DavidMuller** [comment]
Thanks for the pull request @schobster -- this looks like a nice feature.

I agree that tighter integration with boto could make using this package more convenient.  Mainly, I think our concern is keeping the core "request signing" feature as segmented as possible from any additional requirements or third party libs.

I'd be open to an interface like this...

```python
# application_code.py

from aws_requests_auth.aws_auth import AWSRequestsAuth


# this import is strictly optional, but can be used as a convenience
# for people who have boto installed
from aws_requests_auth import boto_utils

auth = AWSRequestsAuth(aws_host='search-service-foobar.us-east-1.es.amazonaws.com',
                       aws_region='us-east-1',
                       aws_service='es',
                       **boto_utils.get_credentials_kwargs_for_aws_requests_auth())
```

Here would be an example implementation of `boto_utils.py`

```python
# boto_utils.py
"""
Functions in this file are included as a convenience for working with AWSRequestsAuth.
External libraries, like boto, that this file imports are not a strict requirement for the
aws-requests-auth package.
"""

import boto3


def get_credentials_kwargs_for_aws_requests_auth():
    """
    Interacts with boto to retrieve AWS credentials, and returns a dictionary of
    kwargs to be used in AWSRequestsAuth
    """
    # do something in boto to get credentials
    credentials_obj = <use-boto-to-do-something>

    return {
        'aws_access_key': credentials_obj.access_key,
        'aws_secret_access_key': credentials_obj.secret_key,
        'aws_token': credentials_obj.token,
    }
```

I think the key here is that this package would not strictly rely on any external packages like boto, but we could provide convenience methods and documentation for people who want to use those packages.  e.g.


```markdown
README.md

# Using Boto To Automatically Gather AWS Credentials

boto is not a strict requirement of `aws-requests-auth`, but if you are using boto we do
provide some convenience methods for using boto to automatically retrieve your 
AWS credentials for you.

<add code example here>
```

**Comment by schobster** [comment]
I like it! That makes sense and makes things even simpler.  I've made the changes as suggested, with some minor tweaks. Just let me know if you'd like any other changes, and thank you for the helpful package.

**Comment by schobster** [comment]
Removed boto3 import which was causing the TravisCI build to fail, sry about that.

**Comment by DavidMuller** [comment]
These changes are included in version 0.3.2 which is now uploaded to pypi

**Pull request merged**
